export { 
    USER_QUERY,
    GET_FRIENDS_QUERY,
 } from './query';

export { 
    ADD_FRIEND_MUTATION, 
    ACCEPT_FRIEND_MUTATION, 
    REJECT_FRIEND_MUTATION,
    REMOVE_FRIEND_MUTATION, 
    REGISTER_MUTATION,
    LOGIN_MUTATION,
    STATUS_UPDATE_MUTATION,
    SENDMESSAGE_MUTATION,
} from './mutations';

export {
    FRIENDSTATUSUPDATE,
    FRIENDUPDATED,
    MESSAGERECEIVED,
} from './subscriptions';